### ISSUE TITLE
Error after running asr-server.py  [undefined symbol: cudaGetDevice]

### ISSUE THREAD

**Issue by ahmetaa** [alphacep/kaldi-websocket-python#2]
Hello, I successfully compiled the project but running 

```
python3 asr_server.py
```
yielded this error:
```
Traceback (most recent call last):
  File "/home/ahmet/projects/kaldi-websocket-python/kaldi_websocket.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/ahmet/projects/kaldi-websocket-python/_kaldi_websocket.so: undefined symbol: cudaGetDevice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asr_server.py", line 6, in <module>
    from kaldi_websocket import Model, KaldiRecognizer
  File "/home/ahmet/projects/kaldi-websocket-python/kaldi_websocket.py", line 17, in <module>
    _kaldi_websocket = swig_import_helper()
  File "/home/ahmet/projects/kaldi-websocket-python/kaldi_websocket.py", line 16, in swig_import_helper
    return importlib.import_module('_kaldi_websocket')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ahmet/projects/kaldi-websocket-python/_kaldi_websocket.so: undefined symbol: cudaGetDevice
Segmentation fault (core dumped)
```

**Comment by nshmyrev** [comment]
Change libs in Makefile to include cuda libraries if you want to run against cuda-enabled kaldi. The libraries should match the ones in kaldi compilation.

**Comment by ahmetaa** [comment]
Thanks Nikolay!

**Comment by lalimili6** [comment]
@ahmetaa @nshmyrev 
Would you mind explain it more? How change cuda libraries?

**Comment by lalimili6** [comment]
I also give this error when make by non cuda kaldi
```kaldi-websocket-python$ ./asr_server.py 
Traceback (most recent call last):
  File "./asr_server.py", line 6, in <module>
    from kaldi_recognizer import Model, KaldiRecognizer
  File "/home/mili/Documents/kaldi-websocket-python/kaldi_recognizer.py", line 15, in <module>
    import _kaldi_recognizer
ImportError: /home/mili/Documents/kaldi-websocket-python/_kaldi_recognizer.so: undefined symbol: vdPowx
```

how can fix these errors?
best regards

**Comment by yondu22** [comment]
I included cuda libs, but still have this error
```
	$(KALDI_ROOT)/src/cudamatrix/kaldi-cudamatrix.a \
	$(KALDI_ROOT)/src/cudadecoder/kaldi-cudadecoder.a \
	$(KALDI_ROOT)/src/cudafeat/kaldi-cudafeat.a \
```

**Comment by nshmyrev** [comment]
@yondu22 you also need to add `-L/usr/local/cuda/lib64 -Wl,-rpath,$/usr/local/cuda/lib64 -lcublas -lcusparse -lcudart -lcurand`

Alternatively, compile kaldi without cuda with ./configure --use-cuda=no

**Comment by binglel** [comment]
> I included cuda libs, but still have this error
> 
> ```
> 	$(KALDI_ROOT)/src/cudamatrix/kaldi-cudamatrix.a \
> 	$(KALDI_ROOT)/src/cudadecoder/kaldi-cudadecoder.a \
> 	$(KALDI_ROOT)/src/cudafeat/kaldi-cudafeat.a \
> ```

I also have this error:
undefined symbol: vdPowx

How did you solve it？Thanks!

**Comment by nshmyrev** [comment]
> undefined symbol: vdPowx

This is due to mkl libraries. Recompile kaldi with openblas or change required libs to mkl.
