### ISSUE TITLE
Run server in Windows

### ISSUE THREAD

**Issue by fels97** [alphacep/kaldi-websocket-python#21]
Hi,

I'm currently trying to start your server directly with the Windows command prompt. I already managed to get it running by copying the compilation process of the dockerfiles and executing everything with the Windows Subsystem for Linux, but I'm interested to get the server working on older systems which don't support WSL without having to create a VM.

When I start the server, I always need to use the WSL for that, because when I try to use cmd, I receive the following error:

	Traceback (most recent call last):
	  File "C:\Users\fels97\Desktop\Programme\SpracherkennungDateien\kaldi-server\websocket\kaldi_recognizer.py", line 14, in swig_import_helper
		return importlib.import_module(mname)
	  File "C:\Users\fels97\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
		return _bootstrap._gcd_import(name[level:], package, level)
	  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
	  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
	ModuleNotFoundError: No module named '_kaldi_recognizer'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "asr_server.py", line 8, in <module>
		from kaldi_recognizer import Model, KaldiRecognizer
	  File "C:\Users\fels97\Desktop\Programme\SpracherkennungDateien\kaldi-server\websocket\kaldi_recognizer.py", line 17, in <module>
		_kaldi_recognizer = swig_import_helper()
	  File "C:\Users\fels97\Desktop\Programme\SpracherkennungDateien\kaldi-server\websocket\kaldi_recognizer.py", line 16, in swig_import_helper
		return importlib.import_module('_kaldi_recognizer')
	  File "C:\Users\fels97\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
		return _bootstrap._gcd_import(name[level:], package, level)
	ModuleNotFoundError: No module named '_kaldi_recognizer'

I think this is due to the missing ATLAS library that's not accessible outside of the WSL.

Can this be solved by using ATLAS for Windows (read that it could be installed using Cygwin), are there any other problems that might occur when trying to do what I do or do I need to take a completely different approach?

Greetings

**Comment by nshmyrev** [comment]
On windows Kaldi works better with Openblas. I personally use mingw on Linux to cross-compile kaldi for Windows, it works fine, but I haven't yet released the setup. It is in the plans though.

If you are ok with VS, you can build everything in VS like Kaldi documentation for Windows describes.

Kaldi also recently added cmake support, I didn't try it yet.

I do not recommend you to use cygwin.

**Comment by fels97** [comment]
I already tried to build Kaldi with VS a while back and it kinda was a chore.

Can you already roughly estimate when you're planning on releasing the cross-compilation setup? Might look into it myself otherwise.

Anyway, thanks for the fast and good advice!

**Comment by nshmyrev** [comment]
End of January likely.

Try cmake build, it should be good I think.
