### ISSUE TITLE
_kaldi_recognizer.so: undefined symbol: vdPowx

### ISSUE THREAD

**Issue by binglel** [alphacep/kaldi-websocket-python#30]
When I run `python asr_server.py`, I get the following error.
`Traceback (most recent call last):
  File "/home/binglel/binglel/kaldi/egs/demo/socket_web_gpu/kaldi_recognizer.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/binglel/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: /home/binglel/binglel/kaldi/egs/demo/socket_web_gpu/_kaldi_recognizer.so: undefined symbol: vdPowx

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asr_server.py", line 8, in <module>
    from kaldi_recognizer import Model, KaldiRecognizer, Gpu
  File "/home/binglel/binglel/kaldi/egs/demo/socket_web_gpu/kaldi_recognizer.py", line 17, in <module>
    _kaldi_recognizer = swig_import_helper()
  File "/home/binglel/binglel/kaldi/egs/demo/socket_web_gpu/kaldi_recognizer.py", line 16, in swig_import_helper
    return importlib.import_module('_kaldi_recognizer')
  File "/home/binglel/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/binglel/binglel/kaldi/egs/demo/socket_web_gpu/_kaldi_recognizer.so: undefined symbol: vdPowx`

Ask for your help. Thanks!

**Comment by nshmyrev** [comment]
If you compiled kaldi with MKL (we recommend openblas instead), you need to preload mkl libraries with LD_PRELOAD, see

https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/748309
